version: '4.1.0'

volumes:
  cloud-postgres:
    driver: local

services:
  postgres:
    image: postgres:9.6
    domainname: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "postgres" ]
      interval: 5s
      timeout: 1s
      retries: 2


#  zipkin:
#    image: openzipkin/zipkin
#    ports:
#      - "9411:9411"