server:
  servlet:
    context-path: /market
  port: 8189
#  see app from url: http://localhost:8189/market/index.html#!/
spring:
  flyway:
    locations: classpath:/db/testdata
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
        trace: true
# see console from url: http://localhost:8189/market/h2-console/
      path: /h2-console

redis:
  hostname: redis-15850.c250.eu-central-1-1.ec2.cloud.redislabs.com
  port: 15850
  password: gCJtMyro3E7LPrdAsxtpQVFpHMBiPKOS

jwt:
  secret: oifh4309f8h324098fh4398gh8h*&TG*#&Gg97rgff98gf983h4f983h487g*&^F&Fu3r
  lifetime: 36000000

integration:
  cart-service:
    url: http://localhost:8191/market-cart