server:
  servlet:
    context-path: /market
  port: 8189

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#  flyway:
#    locations: classpath:/db/migration
#    url: jdbc:postgresql://localhost:5433/postgres
#    schemas: public
#    user: postgres
#    password: postgres
#    connect-retries: 60
#    validate-on-migrate: true

jwt:
  secret: oifh4309f8h324098fh4398gh8h*&TG*#&Gg97rgff98gf983h4f983h487g*&^F&Fu3r
  lifetime: 36000000

redis_cart:
  hostname: redis-15850.c250.eu-central-1-1.ec2.cloud.redislabs.com
  port: 15850
  password: gCJtMyro3E7LPrdAsxtpQVFpHMBiPKOS

integration:
  cart-service:
    url: http://localhost:8191/market-cart




#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
#    username: sa
#    password:
#  jpa: